language: python
python: 
 - 3.6

services: 
  - docker

before-install: 
  - docker pull jupyter/datascience-notebook

script: 
  - ls
  - echo $(pwd)
  - docker run -v $(pwd) jupyter/datascience-notebook /bin/bash -c "echo $(pwd) && make build"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  on:
    branch: master