sudo: required
language: python
python: 
 - 3.6

before_install:
  - gem install jekyll
  - bundle install
  - pip install nbconvert

script:
  - /bin/bash make.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  on:
    branch: master