language: python
python: 
 - 3.6

services: 
  - docker

before-install: 
  - docker pull jupyter/datascience-notebook
  - docker run jupyter/datascience-notebook /bin/sh -c "make build"

script: 
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  on:
    branch: master