sudo: required
language: python
python: 
 - 3.6

services: 
  - docker

script: 
  - ls
  - echo $(pwd)
  - docker run -v $(pwd):/app ubuntu /bin/bash make.sh

# jupyter/datascience-notebook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  on:
    branch: master